---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: 10.0.3.40-10.0.3.50
  METALLB_K8S_GATEWAY_ADDR: 10.0.3.40
  METALLB_TRAEFIK_ADDR: 10.0.3.41
