kind: Secret
ansible_user: ENC[AES256_GCM,data:emHw1MXC,iv:mJry+bKDD2yMmZk8gyzCDLPOvkSSgZZGS3F9ZPGCjN4=,tag:TV1tL7Pg3V/fTsoo1hkMZg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:ge2B/mKKWQ==,iv:g8P5zadZTmbkVMAAaxLuevASh0r/x1fg6RCooYu4Qfw=,tag:Ssju3xYW0+bXUJqgwsH+8w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12urr4exeucvf7kyc7k3f0zfvy4ph4shvmepzgf256zzm8a30nuxqt5g9hy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpaHMzYnY3bDFzRS9MRVh6
            NENXemR6bHYyNGZGQnMxUWMwTUJidlZHWFZjCk1aSEliMUVhNFJFUlJpRlYxOVQy
            aWFRN3NjWCs4VWZ3YjVvZDJwdzdSMUkKLS0tIDNPOWMvNGc2SmhOYk9TcmwzRTJN
            WVhTNzFyYWoyblZVRTllQ2Zsdll0UjAK41Ebp55OVnFnAokzLhLMsI+AIlXN6FcT
            cksjDWvPA+Pd01v9ewbiORrgG7crEopzzoNWNkRgbp3LrSV6CtWfSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-22T16:56:24Z"
    mac: ENC[AES256_GCM,data:VOGYwSuKP2DTa0zWnjXJuKLfwLiTJCga13/vsPSK9ZMkhwKpcSu0Le0cDmQMYbrCbqq2oxCDmD3Mqdog+91YI7d63U+MdDtwcgcvGD2GhLeL70w9eyWkH3Zy7mtDAsXSRZHriSBPajOGDlvol6GhffFo1xQbN7r4fONL3cI+7X0=,iv:g+6rVvGN3zoqeJ35/N0wI8TenqNVfkOp7jx9r7dTgyc=,tag:q4EeE/lkjTZ7cC6nSZZnMw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
