kind: Secret
ansible_user: ENC[AES256_GCM,data:AdAlXwkG,iv:EGWW0Qeit2hogqFhcFcDxDGjzHgLv8Nsil+rPh7Fl5w=,tag:kABrxNimwtItFXXaNCY8CA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:ubi3WBRdSw==,iv:ZNaCMkwFkXBOix7h1evqhVVhiofgJgSwzABNnQ8AdwU=,tag:g40Ere302OMGyJYatMzQNg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12urr4exeucvf7kyc7k3f0zfvy4ph4shvmepzgf256zzm8a30nuxqt5g9hy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBheGE5dndJM2pxRE1SR2Uw
            dEpLWlFMVDF0aFNmcDdndEtZMktRQWI0YVFzCmdqdVZ2RFRvVnNCR29CczFyenNW
            UWRta3B4N0xyVXBHckdabjlFVHNKTmMKLS0tIGprTHZaSTBxM0gvYzRkQmx4Y0ZP
            ZDVHUjJJNVd3VmxXWFlpS0g5NE9TZk0Kgci/oY3Zvyf7vGOlmmGknz6XgiYqVLHY
            OtjpeHdIANYXq6vrlq9VxfoTP6PjOUfABa9oP6Z44On9+fwwBxYkIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-18T10:07:57Z"
    mac: ENC[AES256_GCM,data:ZClFxYWRJFkF8rfwz+Z8T7cOLTLwg6sgvl+UqZd/+4iKmadt4nemaQQL2sxBAiFOkH7gajhDs0dzbofwg/LKbsYv2RVU2h87iy80O8r9oaVWsVZHLm2UwavUVLZ0c/NXpW8BXmflqrwsgqlhaa0tIFRP2y81uapCZ4qDZfP0CWM=,iv:cv6YERpSGMfKAJk4ubelpS3VJHGE/9MQtRz6Zs60Bjk=,tag:ljmy0XL4UCTLQ+y4eTQZ1g==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.2
