kind: Secret
ansible_user: ENC[AES256_GCM,data:RZWndiFz,iv:Fi/1OOAwDETpLf+Ac8GqNoNd4riTte0d8ZtUAaWgg4c=,tag:5E0kT9ZaiXYgSrG/vJeUTQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:UPIE5z8khA==,iv:QSKgqU7O9eegFU0qLXtn00hhPQU1EqIdqavsZzu5fhA=,tag:rYlHanAoEXwwogVXnsJlBQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12urr4exeucvf7kyc7k3f0zfvy4ph4shvmepzgf256zzm8a30nuxqt5g9hy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSSFM4ekNMQ1ZQVFE0dzF0
            dWcxbVVFd3hDMG5PakVYdjIxcitSVjhRa1d3CjBYanlNM0lTVzZUSGowRXZDa2p4
            Rk5hR3YrOFNUZTdMZW1PQ09XVTdIL28KLS0tIG04VlFQYVJpRjFDZ3NMQ1d3Smpr
            TEpzS2RrNkRFZnhENUlqMUw4Q0R3Z2MK/V50lJLtLyDr4Nfsq6QIg7Zg9eVotKJ5
            IvK6m0lmX9LbuvDlLca+4uSoXLhUnVExGXsc0Wa83dc6qlTPFrSkmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-22T16:56:24Z"
    mac: ENC[AES256_GCM,data:2sC+5Y5ANVNXNX4v/1TMSTPbtrCqqGIylmMO4GfVNa8cuvukYGGGsfOgLWd2zak/W1RT2yXXpo0E6xxPggvxII3uui0Sd7K0z4eQP3AghpljhdZohG8B+W6wKVyGZVo57amT5pfi6y0bvWkLtCiCybWkw0j3hZ8U6nwMOD9GqF0=,iv:X4e0PHEjWmo76xdSURCCZgu3/4InwbV2TGy6M7KuEPo=,tag:Efm94mkRGlq4Qhux1gHJ2w==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
